
% A) SET-UP AND PREP
clearvars; clear session; close all; clc;
load 'lfs_data';
rng('default');
%%%%%%%%%%%%%%%%%%%%
% now define the set of variables to use in clustering 
data=[grad, A_level_plus, GCSE_plus,...
    skill1 skill2 skill3 skill4,...
    contemp_short,contemp_long,...
    female,kids_below2, kids_2_9,...
    young,non_white,...
    London,SE,...
    temp,zhc,...
    public_sector,...
    job_search,...
    ];
% We rescale the data so that all variables are between 0 and 1
% it is recommended to do this with clustering analysis
colmin = min(data);
colmax = max(data);
X = rescale(data,'InputMin',colmin,'InputMax',colmax);

nobs=size(X,1);
nvar=size(X,2);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% K-MEDOIDS ESTIMATION USING THE FULL SAMPLE FOR A RANGE OF VaLUES FOR K
cluster_2_8

% SAVE RESULTS INTO AN EXCEL FILE FOR READING INTO STATA

T = table(grad, A_level_plus, GCSE_plus,...
    skill1, skill2, skill3, skill4,...
    contemp_short,contemp_long,...
    female,London,SE,temp,zhc,...
    public_sector,...
    non_white,job_search,...
    kids_below2, kids_2_9,age_lt_30,...
    IDX_2,...
weight);
filename = 'm_to_e_alt_1.xlsx';
writetable(T,filename,'Sheet',1);



